# Generated by Django 5.2.17 on 2026-08-14 23:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('invoices', '0010_alter_invoice_marked_paid_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctrineFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Gila - T2'", max_length=100)),
                ('hull_type_id', models.PositiveIntegerField(help_text='EVE type ID of the hull')),
                ('hull_type_name', models.CharField(blank=True, default='', max_length=100)),
                ('dna', models.TextField(blank=True, default='', help_text='EVE fitting DNA string (fitting -> export to clipboard). Optional.')),
                ('skill_tier', models.CharField(blank=True, default='', help_text="Label for skill requirements, e.g. 'T2', 'T1', 'Newbie'", max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('rent_rate_hourly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ISK per hour for contract/hangar rentals. 0 = hourly not offered.', max_digits=20)),
                ('rent_rate_daily', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ISK per day for contract/hangar rentals. 0 = daily not offered.', max_digits=20)),
                ('rent_rate_weekly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ISK per week for contract/hangar rentals. 0 = weekly not offered.', max_digits=20)),
                ('free_use_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ISK per billing period for free-use hangar rentals. Set 0 to disable free-use.', max_digits=20)),
                ('free_use_billing_period', models.CharField(choices=[('hourly', 'Per hour'), ('daily', 'Per day'), ('weekly', 'Per week')], default='daily', help_text='Billing period for free-use rentals (hourly/daily/weekly).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctrine Fit',
                'verbose_name_plural': 'Doctrine Fits',
                'ordering': ['name'],
                'permissions': [('access_shipfinance', 'Can Access the Ship Finance App'), ('manage_shipfinance', 'Can Manage Ship Finance (admin)'), ('use_rent', 'Can Rent Ships'), ('use_finance', 'Can Finance Ships')],
            },
        ),
        migrations.CreateModel(
            name='FreeUseHangar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hangar_division', models.PositiveSmallIntegerField(default=1, help_text='Corp hangar division (1-7). This division at ANY station is a rental hangar.', unique=True)),
                ('ship_name_prefix', models.CharField(default='.BANR', help_text="Ships in this division whose name starts with this prefix are rental ships. Others are ignored. E.g. '.BANR' matches '.BANR Gila 1'.", max_length=20)),
                ('require_return_to_origin', models.BooleanField(default=False, help_text='If True, the rental only closes when the ship is returned to the SAME station it was rented from. Returning to a different station keeps the rental open until the ship is back at the origin.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental Hangar',
                'verbose_name_plural': 'Rental Hangars',
                'ordering': ['hangar_division'],
            },
        ),
        migrations.CreateModel(
            name='FinanceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Gila Finance - 3 month'", max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Ship price in ISK', max_digits=20)),
                ('term_months', models.PositiveIntegerField(default=3, help_text='Number of monthly installments')),
                ('interest_type', models.CharField(choices=[('flat', 'Flat add-on'), ('apr', 'APR (declining balance)')], default='flat', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10, help_text='Flat % add-on, or APR % (annual)', max_digits=6)),
                ('insurance_enabled', models.BooleanField(default=True)),
                ('insurance_premium_rate', models.DecimalField(decimal_places=2, default=5, help_text='Insurance premium as % of principal', max_digits=6)),
                ('insurance_coverage', models.CharField(choices=[('remaining_balance', 'Remaining balance at time of loss'), ('principal', 'Original principal'), ('flat_amount', 'Flat amount')], default='remaining_balance', max_length=20)),
                ('insurance_flat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Used only when coverage = FLAT_AMOUNT', max_digits=20)),
                ('terms_text', models.TextField(blank=True, default='', help_text='Fine print shown to members before they accept.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctrine_fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_offers', to='shipfinance.doctrinefit')),
            ],
            options={
                'verbose_name': 'Finance Offer',
                'verbose_name_plural': 'Finance Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField(help_text='ESI asset item_id', unique=True)),
                ('item_name', models.CharField(blank=True, default='', help_text='Current ship name (display only, not used for tracking)', max_length=100)),
                ('location_id', models.BigIntegerField(help_text='Home station/structure location_id')),
                ('location_name', models.CharField(blank=True, default='', max_length=200)),
                ('hangar_division', models.PositiveSmallIntegerField(default=1, help_text='Corp hangar division (1-7) where the ship lives')),
                ('state', models.CharField(choices=[('available', 'Available'), ('out_rent', 'Out on rental'), ('out_finance', 'Out on finance'), ('sold', 'Sold (finance paid off)'), ('lost', 'Lost (unaccounted)'), ('destroyed', 'Destroyed')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctrine_fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='shipfinance.doctrinefit')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ship Stock',
                'verbose_name_plural': 'Ship Stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_mode', models.CharField(choices=[('contract', 'Contract to member'), ('hangar_request', 'Hangar access (request)'), ('free_use', 'Self-service rental hangar')], default='contract', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('return_detected_at', models.DateTimeField(blank=True, null=True)),
                ('origin_location_id', models.BigIntegerField(blank=True, null=True)),
                ('origin_location_name', models.CharField(blank=True, default='', max_length=200)),
                ('billing_period', models.CharField(choices=[('hourly', 'Per hour'), ('daily', 'Per day'), ('weekly', 'Per week')], default='daily', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ISK per billing period', max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('destroyed', 'Destroyed'), ('lost', 'Lost (unaccounted)'), ('closed', 'Closed')], default='active', max_length=20)),
                ('terms_acknowledged', models.BooleanField(default=False)),
                ('terms_text', models.TextField(blank=True, default='')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_agreement', to='invoices.invoice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
                ('member_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_rentals', to='eveonline.evecharacter')),
                ('ship_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='shipfinance.shipstock')),
            ],
            options={
                'verbose_name': 'Rental Agreement',
                'verbose_name_plural': 'Rental Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('georgeforge_order_id', models.BigIntegerField(blank=True, help_text='GeorgeForge order ID if this is an installment plan for a GF order.', null=True)),
                ('georgeforge_item_name', models.CharField(blank=True, default='', help_text='Item name from the GeorgeForge order (for display).', max_length=200)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('term_months', models.PositiveIntegerField()),
                ('interest_type', models.CharField(choices=[('flat', 'Flat add-on'), ('apr', 'APR (declining balance)')], max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('insurance_purchased', models.BooleanField(default=False)),
                ('insurance_premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('insurance_coverage', models.CharField(choices=[('remaining_balance', 'Remaining balance at time of loss'), ('principal', 'Original principal'), ('flat_amount', 'Flat amount')], default='remaining_balance', max_length=20)),
                ('insurance_flat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid off'), ('defaulted', 'Defaulted'), ('destroyed', 'Destroyed (no insurance)'), ('destroyed_insured', 'Destroyed (insured)'), ('closed', 'Closed')], default='active', max_length=25)),
                ('paid_off_date', models.DateTimeField(blank=True, null=True)),
                ('terms_acknowledged', models.BooleanField(default=False)),
                ('terms_text', models.TextField(blank=True, default='')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_insurance_agreement', to='invoices.invoice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to=settings.AUTH_USER_MODEL)),
                ('member_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_finances', to='eveonline.evecharacter')),
                ('finance_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='shipfinance.financeoffer')),
                ('ship_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finances', to='shipfinance.shipstock')),
            ],
            options={
                'verbose_name': 'Finance Agreement',
                'verbose_name_plural': 'Finance Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipfinance_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('finance_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='shipfinance.financeagreement')),
                ('rental_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='shipfinance.rentalagreement')),
                ('ship_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='shipfinance.shipstock')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('due_date', models.DateTimeField()),
                ('is_final', models.BooleanField(default=False)),
                ('finance_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='shipfinance.financeagreement')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_installment', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Finance Installment',
                'verbose_name_plural': 'Finance Installments',
                'ordering': ['installment_number'],
                'unique_together': {('finance_agreement', 'installment_number')},
            },
        ),
    ]
